SIMPLE_DICT={
    "conservation": "protection",
    "critical": "very important",
    "threat": "danger",
    "preserving": "protecting",
    "essential": "important",
    "biodiversity": "variety of life",
    "coexist": "live together",
    "delicate": "fragile",
    "ecosystems": "natural systems",
    "collapse": "fall apart",
    "depend on": "rely on",
    "combatting": "fighting",
    "deforestation": "cutting down trees",
    "contribute": "cause",
    "mitigate": "reduce",
    "sustainable": "long-lasting",
    "improves": "makes better",
    "preserved": "protected",
    "create awareness": "make people aware",
    "promote": "encourage",
    "necessity": "must",
    "safeguarding": "protecting",
     "valuable": "important",
    "develop": "build",
    "imagination": "creativity",
    "personal growth": "self-improvement",
    "spark": "start",
    "advanced": "difficult",
    "academic": "school-related",
    "specialized": "specific",
    "benefits": "advantages",
    "expansion": "growth",
    "inspire": "encourage",
    "challenge": "test",
    "cultures": "societies",
    "histories": "pasts",
    "scientific discoveries": "science findings",
    "transformed": "changed",
    "modern": "current",
    "exception": "special case",
    "confined": "limited",
    "limitless": "endless",
    "opportunities": "chances",
    "advantage": "benefit",
    "virtually": "almost",
    "interactive": "hands-on",
    "engaging": "interesting",
    "effective": "useful",
    "encourages": "promotes",
    "collaboration": "working together",
    "communication": "talking or sharing ideas",
    "essential" : "very important",
    "influences": "affects",
    "communicate": "talk or share information",
  "across": "from one place to another",
  "rely": "depend",
  "research": "study",
  "advanced": "high-level or modern",
  "diagnose": "find a disease or problem",
  "efficiently": "in a better and faster way",
  "available": "easy to get",
  "connect": "join or link",
  "evolved": "developed or changed",
  "streaming": "watching online",
  "automating": "doing automatically",
  "complex": "difficult",
  "opportunities": "chances",
  "excessive": "too much",
  "convenient": "easy to use",
  "quality": "standard or level",
  "improve": "make better"
}

